### PR TITLE
Re-enable Java bindings

### PR DESCRIPTION
**Pull request by llimeht**
This PR updates the build of the Java bindings to be compatible with modern JDK (javah for building the JNI header is no more, etc) and re-enables building the Java bindings.

### CODE REVIEW

**Comment by mkoennecke** [comment]
A very laudable effort. One question though: in the java bindings directory there is a little test program for the Java binding. To be run manually, has never been integrated into something. My question  now: does this still run?

**Comment by llimeht** [comment]
`TestJapi.java` does indeed execute successfully. It's included in the [Debian package CI tests](https://salsa.debian.org/science-team/nexus/blob/master/debian/tests/libnexus-java) and seems to run fine. I've not yet looked at how to integrate it into the cmake build system or verified that it does indeed exit with an error code if the test fails.

**Comment by mkoennecke** [comment]
Then I am happy with this change.

**Comment by mkoennecke** [comment]
This has been merged into pull request 4.4.4

**Pull request closed without merging**
