### PR TITLE
Make check work for copied datatype IDs to fix nexusformat/code#386

### PR DESCRIPTION
**Pull request by PeterC-DLS**

### CODE REVIEW

**Comment by eugenwintersberger** [comment]
Hi Peter, I guess that the array attribute tests for HDF4 and MXML are supposed to fail. Am I right?

**Comment by PeterC-DLS** [comment]
Maybe: best to ask whomever added the array attribute support.

**Comment by zjttoefs** [comment]
In the test/testsuite.at it is actually expecting the legacy backends to fail with appropriate error messages.
Some tests are skipped as well. To the outside observer all should be passing.

**Comment by eugenwintersberger** [comment]
Thanks Tobias - this helps. I can mark the tests as "must fail"  in which case all tests should pass.

**Pull request merged**
